### ISSUE TITLE
notes on using express-winston and @elastic/ecs-winston-format

### ISSUE THREAD

**Issue by trentm** [elastic/ecs-logging-js#34]
I did some exploration of using [@elastic/ecs-winston-format](https://github.com/elastic/ecs-logging-js/tree/master/loggers/winston) here with the [express-winston](https://github.com/bithavoc/express-winston) middleware package. I'll collect notes here in case they are useful for:

1. anyone that wants to use these two modules together; and
2. possible future dev work to integrate support and/or docs for this.

Currently I'm not proposing integrating docs about using express-winston with @elastic/ecs-winston-format because I don't think it is a very satisfying integration (at least not yet).

**Comment by trentm** [comment]
A quick first pass:

```js
// Adapted (heavily) from https://github.com/bithavoc/express-winston#examples

const ecsFormat = require('../') // @elastic/ecs-winston-format
var express = require('express')
var expressWinston = require('express-winston')
var winston = require('winston')

var logger = winston.createLogger({
  format: ecsFormat({ convertReqRes: true }),
  transports: [
    new winston.transports.Console()
  ]
})

var app = express();

// express-winston logger makes sense BEFORE the router
app.use(expressWinston.logger({ winstonInstance: logger }))

app.get('/error', function(req, res, next) {
  return next(new Error("boom"))
});
app.get('/', function(req, res, next) {
  res.setHeader('Foo', 'Bar')
  res.write('hi')
  res.end()
});

// express-winston errorLogger makes sense AFTER the router.
app.use(expressWinston.errorLogger({ winstonInstance: logger }))

app.listen(3000, function(){
  logger.info(`listening at http://localhost:${this.address().port}`)
});
```

yields request log output like the following:

```
% node express.js  | jq .
...
{
  "@timestamp": "2021-01-15T22:19:44.467Z",
  "log.level": "info",
  "message": "HTTP GET /",
  "ecs": {
    "version": "1.5.0"
  },
  "meta": {
    "req": {
      "url": "/",
      "headers": {
        "host": "localhost:3000",
        "user-agent": "curl/7.64.1",
        "accept": "*/*"
      },
      "method": "GET",
      "httpVersion": "1.1",
      "originalUrl": "/",
      "query": {}
    },
    "res": {
      "statusCode": 200
    },
    "responseTime": 2
  }
}
```

That minimally matches the ECS logging spec, so could pass. The unsatisfying part of this is that express-winston puts the `req` / `res` captured data under a top-level "meta" key, which means the [current ecs-winston-format transform](https://github.com/elastic/ecs-logging-js/blob/65f42747f7a42e491943ca1ba2f512c27ca3602a/loggers/winston/index.js#L34-L47) can not capture those as ECS HTTP fields.

**Comment by trentm** [comment]
Error logging, as well, works, but includes non-JSON output and captures a *lot* of data (by design). E.g. with a `curl localhost:3000/errors` for the server above:

```
{
  "@timestamp": "2021-01-15T22:18:29.399Z",
  "log.level": "error",
  "message": "middlewareError",
  "ecs": {
    "version": "1.5.0"
  },
  "meta": {
    "error": {},
    "level": "error",
    "message": "uncaughtException: boom\nError: boom\n    at /Users/trentm/el/ecs-logging-js/loggers/winston/examples/express.js:35:15\n    at Layer.handle [as handle_request] (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js:335:12)\n    at next (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js:275:10)\n    at /Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express-winston/index.js:428:9\n    at Layer.handle [as handle_request] (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js:95:5)",
    "stack": "Error: boom\n    at /Users/trentm/el/ecs-logging-js/loggers/winston/examples/express.js:35:15\n    at Layer.handle [as handle_request] (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js:95:5)\n    at next (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js:95:5)\n    at /Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js:335:12)\n    at next (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js:275:10)\n    at /Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express-winston/index.js:428:9\n    at Layer.handle [as handle_request] (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js:95:5)",
    "exception": true,
    "date": "Fri Jan 15 2021 14:18:29 GMT-0800 (Pacific Standard Time)",
    "process": {
      "pid": 48552,
      "uid": 501,
      "gid": 20,
      "cwd": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples",
      "execPath": "/Users/trentm/.nvm/versions/node/v10.23.0/bin/node",
      "version": "v10.23.0",
      "argv": [
        "/Users/trentm/.nvm/versions/node/v10.23.0/bin/node",
        "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/express.js"
      ],
      "memoryUsage": {
        "rss": 46510080,
        "heapTotal": 24936448,
        "heapUsed": 15907168,
        "external": 642616
      }
    },
    "os": {
      "loadavg": [
        1.11767578125,
        1.28173828125,
        1.3310546875
      ],
      "uptime": 2094642
    },
    "trace": [
      {
        "column": 15,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/express.js",
        "function": null,
        "line": 35,
        "method": null,
        "native": false
      },
      {
        "column": 5,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js",
        "function": "Layer.handle [as handle_request]",
        "line": 95,
        "method": "handle [as handle_request]",
        "native": false
      },
      {
        "column": 13,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/route.js",
        "function": "next",
        "line": 137,
        "method": null,
        "native": false
      },
      {
        "column": 3,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/route.js",
        "function": "Route.dispatch",
        "line": 112,
        "method": "dispatch",
        "native": false
      },
      {
        "column": 5,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js",
        "function": "Layer.handle [as handle_request]",
        "line": 95,
        "method": "handle [as handle_request]",
        "native": false
      },
      {
        "column": 22,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js",
        "function": null,
        "line": 281,
        "method": null,
        "native": false
      },
      {
        "column": 12,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js",
        "function": "Function.process_params",
        "line": 335,
        "method": "process_params",
        "native": false
      },
      {
        "column": 10,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js",
        "function": "next",
        "line": 275,
        "method": null,
        "native": false
      },
      {
        "column": 9,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express-winston/index.js",
        "function": null,
        "line": 428,
        "method": null,
        "native": false
      },
      {
        "column": 5,
        "file": "/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js",
        "function": "Layer.handle [as handle_request]",
        "line": 95,
        "method": "handle [as handle_request]",
        "native": false
      }
    ],
    "req": {
      "url": "/error",
      "headers": {
        "host": "localhost:3000",
        "user-agent": "curl/7.64.1",
        "accept": "*/*"
      },
      "method": "GET",
      "httpVersion": "1.1",
      "originalUrl": "/error",
      "query": {}
    }
  }
}
{
  "@timestamp": "2021-01-15T22:18:29.401Z",
  "log.level": "info",
  "message": "HTTP GET /error",
  "ecs": {
    "version": "1.5.0"
  },
  "meta": {
    "req": {
      "url": "/error",
      "headers": {
        "host": "localhost:3000",
        "user-agent": "curl/7.64.1",
        "accept": "*/*"
      },
      "method": "GET",
      "httpVersion": "1.1",
      "originalUrl": "/error",
      "query": {}
    },
    "res": {
      "statusCode": 500
    },
    "responseTime": 3
  }
}
Error: boom
    at /Users/trentm/el/ecs-logging-js/loggers/winston/examples/express.js:35:15
    at Layer.handle [as handle_request] (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js:95:5)
    at /Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/index.js:275:10)
    at /Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express-winston/index.js:428:9
    at Layer.handle [as handle_request] (/Users/trentm/el/ecs-logging-js/loggers/winston/examples/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by trentm** [comment]
We could start to get closer on ECS HTTP fields via express-winston's `dynamicMeta`, e.g.:

```js
const ecsHelpers = require('../../../helpers')

// ...

app.use(expressWinston.logger({
  winstonInstance: logger,
  dynamicMeta: function (req, res) {
    const meta = {}
    ecsHelpers.formatHttpRequest(meta, req)
    ecsHelpers.formatHttpResponse(meta, res)
    return meta
  }
})

// ...
```

which yields:

```
{
  "@timestamp": "2021-01-15T22:37:22.267Z",
  "log.level": "info",
  "message": "HTTP GET /",
  "ecs": {
    "version": "1.5.0"
  },
  "meta": {
    "req": {
      "url": "/",
      "headers": {
        "host": "localhost:3000",
        "user-agent": "curl/7.64.1",
        "accept": "*/*"
      },
      "method": "GET",
      "httpVersion": "1.1",
      "originalUrl": "/",
      "query": {}
    },
    "res": {
      "statusCode": 200
    },
    "responseTime": 1,
    "http": {
      "version": "1.1",
      "request": {
        "method": "get",
        "headers": {
          "host": "localhost:3000",
          "accept": "*/*"
        }
      },
      "response": {
        "status_code": 200,
        "headers": {
          "x-powered-by": "Express",
          "foo": "Bar"
        }
      }
    },
    "url": {
      "full": "http://localhost:3000/",
      "path": "/",
      "domain": "localhost"
    },
    "user_agent": {
      "original": "curl/7.64.1"
    }
  }
}
```

But again, that unsatisfyingly adds *both* our dynamicMeta and that from express-winston itself.

**Comment by trentm** [comment]
Another potential concern is that express-winston currently says it is looking for a maintainer. I don't know if there will be a reasonable intersection of express-winston and @elastic/ecs-winston-format users.

I'm closing this for now. We can re-open if there is interest.
